Pinterest_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Include authentications app URLs
    path('pinterest/', include('authentications.urls')),
    # Include PostByUser app URLs with a better prefix
    path('pinterest/posts/', include('PostsByUser.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PostsByUser/urls.py
# PostByUser/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('create_board/', views.create_board, name='create_board'),
    path('board_list/', views.board_list, name='board_list'),
    path('create_pin/', views.create_pin,
         name="create_pin"),  # Ensure name is set
    path('list_pins', views.list_pins, name='list_pins'), path(
        'update_pin/<int:pin_id>/', views.update_pin, name='update_pin'),
    path('delete_pin/<int:pin_id>/', views.delete_pin, name='delete_pin'),
    path('',views.home,name= 'home_page'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/like/', views.like_post, name='like_post'),
    path('post/<int:image_post_id>/add_comment/',
         views.add_comment, name='add_comment'),
    path('post/<int:image_post_id>/list_comments/',
         views.list_comments, name='list_comments'),

         # this is for the rest of the profile ones
    path('profile/<int:pk>/', views.profile, name='profile'),
    path('profile/follow/<int:user_id>/',
         views.adding_followers, name='adding_followers'),
    path('profile/unfollow/<int:following_id>/',
    
         views.unfollowing, name='unfollowing'),
    path('profile/removefollower/<int:follower_id>/',
         views.removing_follower, name='removing_follower'),
]

authentications/urls.py
from django.urls import path
from .views import register, user_login,home,user_logout

urlpatterns = [
    path('',home, name='home'),
    path('register/', register, name='register'),
    path('login/', user_login, name='user_login'),
    path('logout/',user_logout,name='log_out')
    # Add other URLs as needed
]

authentications/models.py
from django.db import models

# Create your models here.
# Use PermissionsMixin for Django >= 2.0
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager


# Inherit from PermissionsMixin for Django >= 2.0
class User(AbstractBaseUser, PermissionsMixin):
    user_image = models.ImageField(blank=True, upload_to='userimages/')
    email = models.EmailField(verbose_name='email',
                              max_length=255, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_of_birth = models.DateField(blank=False, null=False)  # Make required
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'date_of_birth']

    def __str__(self):
        return self.email

authentications/forms.py
from django import forms
from .models import User
from datetime import datetime
from django.contrib.auth.password_validation import validate_password


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Enter password'}))
    date_of_birth = forms.DateField(
        widget=forms.DateInput(
            attrs={'type': 'date', 'placeholder': 'YYYY-MM-DD', 'class': 'form-control'}),
        input_formats=['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y']
    )

    def clean_password(self):
        password = self.cleaned_data.get('password')
        validate_password(password)  # Basic validation
        return password

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                "This email address is already in use. Please use a different email.")
        return email

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'date_of_birth']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter email'}),
            # You can add more widgets for other fields here as needed
        }

authentications/views.py
from django.contrib.auth import logout
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from .models import User

from django.shortcuts import render, redirect
from .forms import RegistrationForm


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            date_of_birth = form.cleaned_data['date_of_birth']

            user = User.objects.create_user(
                email=email,
                username=username,
                password=password,
                date_of_birth=date_of_birth
            )

            # Authenticate and login the user after registration
            # user = authenticate(request, username=username, password=password)

            login(request, user)
            request.session['registration_success'] = True
            return redirect('home')  # Redirect to home after login

    else:
        form = RegistrationForm()

    return render(request, 'index.html', {'form': form, 'domain': 'signup', 'error_message': form.errors})


def user_login(request):
    error_message = None  # Initialize error message
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to the home page after login
            # Assuming 'home' is the URL name for home.html
            return redirect('home')
        else:
            error_message = "Invalid username or password"

    # Render the login overlay with the error message if exists
    return render(request, 'index.html', {'login_error_message': error_message, 'domain': 'login'})


@login_required
def user_logout(request):
    logout(request)
    return redirect('register')


@login_required
def home(request):
    registration_success = request.session.pop('registration_success', False)
    context = {
        'registration_success': registration_success} if registration_success else {}

    return render(request, 'home.html', context)

authentications/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Welcome to Pinterest</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/home.css" %}">
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/9ab1fedf81.js" crossorigin="anonymous"></script>
    
    <style>
      #boardslist,
      #createboard {
        display: none;
      }
      
    </style>
    
  </head>
  <body>
    <header>
      <div class="nav-bar">
      <div><a href=""><img
                src="{% static "img/Pinterest_Favicon.webp" %}"
                alt=""
                width="25px"
                height="25px"
                style="border-radius: 50%"
              /></a></div>
      <div><a href="">Home</a></div>
      <div><a href="">Explore</a></div>
      <div><a href="{% url 'create_pin' %}">Create</a></div>
      <input type="text" name="" id="" placeholder="Search" />
      <div><a href=""><i class="fa-solid fa-bell"></i></a></div>
      <div><a href=""><i class="fa-solid fa-comment-dots"></i></a></div>
      <div><a href="{% url 'profile' pk=user.id %}">
        {% if user.user_image and user.user_image.url  %}
                <img src="{{ user.user_image.url }}" alt="" 
                width="25px"
                height="25px"
                style="border-radius: 50%"
                >
                {% else %}
                <img src="{% static "img/blankimage.jpg" %}" alt=""
                width="25px"
                height="25px"
                style="border-radius: 50%"
                >
                {% endif %}
      </a></div>
               
      <div id='toggling'><a href="" ><i class="fas fa-angle-down"></i
            ></a></div>
    </div>
    </header>
    

    
    {% csrf_token %} {% if request.user.is_authenticated %}
    <h1 class='welcome' style="text-align:center;">Welcome to Pinterest, {{ request.user.username }}</h1>
     {% comment %} <a href="{% url 'create_pin' %}">create_pin</a>
    <a href="{% url "home_page" %}">home page</a> {% endcomment %}
    <!-- Button to fetch the create board form -->
    
    <div class="displayingboards">
      <button id="fetchCreateBoardForm">Create Board</button>

    <button id="boarddisplay">Board List</button>
    </div>
    {% else %}
    <p>You are not logged in. Please log in to access your boards.</p>
    <a href="{% url 'user_login' %}">Login</a>
    {% endif %}

    <!-- Div to render the create board form -->
    <div id="createboard">

    </div>

    <div id="boardslist">
      <h1>Your Boards {{ user }}</h1>
      <ul>
        {% for board in boards %}
        <li>{{ board.name }}</li>
        <li>{{ board.description }}</li>
        {% endfor %}
      </ul>
    </div>
    {% comment %} <a href="{% url "log_out" %}">Log out</a> {% endcomment %}
    {% comment %} <a href="{% url "profile" %}">Profiles</a> {% endcomment %}
    <div class="sidebar" id="sideone">
      <p>Currently in</p>
      <a href="{% url 'profile' pk=user.id %}" class='profilenavigation'>
            {% if user.user_image and user.user_image.url  %}
                <img src="{{ user.user_image.url }}" alt="" 
                width="55px"
                height="55px"
                style="border-radius: 50%;object-fit:cover;"
                >
                {% else %}
                <img src="{% static "img/blankimage.jpg" %}" alt=""
                width="55px"
                height="55px"
                style="border-radius: 50%;object-fit:cover;"
                >
                {% endif %}
                <div class='profilenames'>
                  {{user.username}}
                  <p>Personal</p>
                  <p>{{ user.email }}</p>
                </div>
            </a>
      <p>Your accounts</p>
      <div class="yourAccounts">
        <button>Add account</button>
      <button>Convert to bussiness</button>
      </div>
      <p>More options</p>
      <div class="moreOptions">
        <p>Settings</p>
        <p>Tune your home feed</p>
        <p>Install your home feed</p>
        <p>Install the Chrome app</p>
        <p>your privacy rights</p>
        <p>Get help</p>
        <p>See terms of service</p>
        <p>See privacy policy</p>
        <p>Be a beta tester</p>
        <a href="{% url "log_out" %}">Log out</a>
      </div>
    </div>
    <div class="container"></div>
     
    
    <script>
      
      var imagesurl ='{% url 'home_page' %}'; 
      var boards_url = "{% url 'board_list' %}";
      var createboardurl = "{% url 'create_board' %}";
    </script>
    <script src="{% static 'js/home.js' %}"></script>
  </body>
</html>

authentications/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Login</title>
  </head>
  <body>
    <h2>Login</h2>
    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}
    <form method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" id="username" name="username" required /><br />
      <label for="password">Password:</label>
      <input type="password" id="password" name="password" required /><br />
      <button type="submit">Login</button>
    </form>
  </body>
</html>

authentications/templates/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Sign Up Form</title>
    <style>
      .error-message {
        color: red;
        font-size: 14px;
        margin-top: 5px;
      }
      .overlay {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(
          0,
          0,
          0,
          0.5
        ); /* semi-transparent black overlay */
        display: none; /* Initially hidden */
        justify-content: center;
        align-items: center;
      }

      .container {
        max-width: 400px;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 20px;
        background-color: #f9f9f9;
        text-align: center;
      }

      .container h2,
      .container h5 {
        margin-top: 0;
      }
      .cross button {
        float: right;
        width: 40px;
        height: 40px;
        background-color: red;
        outline: none;
        border: none;
        border-radius: 5px;
        color: #fff;
      }
      .container label {
        display: block;
        margin-bottom: 5px;
        font-weight: bold;
        text-align: left;
        width: 100%; /* Ensure labels span the full width */
      }

      .container input[type="text"],
      .container input[type="password"],
      .container input[type="email"],
      .container select {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 3px;
        box-sizing: border-box;
      }

      .signup {
        width: 100%;
        padding: 10px;
        border: none;
        border-radius: 3px;
        background-color: #4caf50;
        color: white;
        font-size: 16px;
        cursor: pointer;
      }

      .signup:hover {
        background-color: #45a049;
      }
    </style>
  </head>
  <body>
    <button onclick="toggleForm()">Sign Up</button>

    <div id="overlay" class="overlay">
      <div class="container">
        <h2 class="cross">
          Register <button type="button" value="X" id="cutting">X</button>
        </h2>

        <form id="registrationForm" method="post">
          {% csrf_token %}
          <h2>Welcome to Pinterest</h2>
          <h5>Find new ideas to try</h5>
          <label for="id_email">Email:</label>
          {{ form.email }} {% if form.errors.email %}
          <div class="error-message">{{ form.errors.email }}</div>
          {% endif %}
          <label for="id_username">Username:</label>
          {{ form.username }} {% if form.errors.username %}
          <div class="error-message">{{ form.errors.username }}</div>
          {% endif %}
          <label for="id_password">Password:</label>
          {{ form.password }} {% if form.errors.password %}
          <div class="error-message">{{ form.errors.password }}</div>
          {% endif %}
          <label for="id_date_of_birth">Birthdate</label>
          {{ form.date_of_birth }} {% if form.errors.date_of_birth %}
          <div class="error-message">{{ form.errors.date_of_birth }}</div>
          {% endif %}
          <button type="submit" class="signup" id="signupButton">
            Sign Up
          </button>
        </form>
      </div>
    </div>

    <script>
      var errors = document.querySelectorAll(".error-message");
      if (errors.length > 0) {
        overlay.style.display = "flex";
      }

      function toggleForm() {
        var overlay = document.getElementById("overlay");

        overlay.style.display =
          overlay.style.display === "none" || overlay.style.display === ""
            ? "flex"
            : "none";
      }

      function submitForm() {
        var form = document.getElementById("registrationForm");
        form.submit();
      }

      document.getElementById("cutting").addEventListener("click", function () {
        var overlay = document.getElementById("overlay");
        overlay.style.display = "none";
      });

      document
        .getElementById("signupButton")
        .addEventListener("click", function () {
          submitForm();
        });
    </script>
  </body>
</html>